### ISSUE TITLE
ILIAS_8 / Notifications

### ISSUE THREAD

**Issue by mstuder** [studer-raimann/AttendanceList#3]
@dhouhahoussi 

Nutzt ihr die Notifications? Falls ja, in welcher Form? Die Momentane umfangreiche Implementierung habe ich für den ILIAS_8-Release entfernt.

**Comment by dhouhahoussi** [comment]
Hallo lieber Martin,

ich habe nachgefragt. Nein das wird nicht genutzt bei uns.
Liebe Grüße
Dhouha

Von: Martin Studer ***@***.***>
Gesendet: Mittwoch, 22. November 2023 15:50
An: fluxapps/AttendanceList ***@***.***>
Cc: Houssi, Dhouha ***@***.***>; Mention ***@***.***>
Betreff: [fluxapps/AttendanceList] ILIAS_8 / Notifications (Issue #3)


@dhouhahoussi<https://github.com/dhouhahoussi>

Nutzt ihr die Notifications? Falls ja, in welcher Form? Die Momentane umfangreiche Implementierung habe ich für den ILIAS_8-Release entfernt.

**Comment by mstuder** [comment]
Danke für die Rückmeldung!
